<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
    <title><?php echo $this->doc()->title ?> - Flywheel Backend System</title>
    <link href="<?php echo $this->doc()->getBaseUrl(); ?>assets/css/main.css" rel="stylesheet" type="text/css" />

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>

    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/spinner/ui.spinner.js"></script>
    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/spinner/jquery.mousewheel.js"></script>

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>

    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/charts/excanvas.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/charts/jquery.sparkline.min.js"></script>

    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/forms/uniform.js"></script>
    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/forms/jquery.cleditor.js"></script>
    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/forms/jquery.validationEngine-en.js"></script>
    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/forms/jquery.validationEngine.js"></script>
    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/forms/jquery.tagsinput.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/forms/autogrowtextarea.js"></script>
    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/forms/jquery.maskedinput.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/forms/jquery.dualListBox.js"></script>
    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/forms/jquery.inputlimiter.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/forms/chosen.jquery.min.js"></script>

    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/wizard/jquery.form.js"></script>
    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/wizard/jquery.validate.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/wizard/jquery.form.wizard.js"></script>

    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/uploader/plupload.js"></script>
    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/uploader/plupload.html5.js"></script>
    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/uploader/plupload.html4.js"></script>
    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/uploader/jquery.plupload.queue.js"></script>

    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/tables/datatable.js"></script>
    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/tables/tablesort.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/tables/resizable.min.js"></script>

    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/ui/jquery.tipsy.js"></script>
    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/ui/jquery.collapsible.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/ui/jquery.prettyPhoto.js"></script>
    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/ui/jquery.progress.js"></script>
    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/ui/jquery.timeentry.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/ui/jquery.colorpicker.js"></script>
    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/ui/jquery.jgrowl.js"></script>
    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/ui/jquery.breadcrumbs.js"></script>
    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/ui/jquery.sourcerer.js"></script>

    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/calendar.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/plugins/elfinder.min.js"></script>

    <script type="text/javascript" src="<?php echo $this->doc()->getBaseUrl(); ?>assets/js/custom.js"></script>

</head>

<body>

<!-- Style switcher -->
<!--
<div class="switcher">
    <a href="#" title="" class="pat1"><img src="<?php echo $this->doc()->getBaseUrl(); ?>assets/images/switcher/2.png" alt="" /></a>
    <a href="#" title="" class="pat2"><img src="<?php echo $this->doc()->getBaseUrl(); ?>assets/images/switcher/3.png" alt="" /></a>
    <a href="#" title="" class="pat3"><img src="<?php echo $this->doc()->getBaseUrl(); ?>assets/images/switcher/4.png" alt="" /></a>
    <a href="#" title="" class="pat4"><img src="<?php echo $this->doc()->getBaseUrl(); ?>assets/images/switcher/5.png" alt="" /></a>
    <a href="#" title="" class="pat5"><img src="<?php echo $this->doc()->getBaseUrl(); ?>assets/images/switcher/6.png" alt="" /></a>
    <a href="#" title="" class="pat6"><img src="<?php echo $this->doc()->getBaseUrl(); ?>assets/images/switcher/7.png" alt="" /></a>
    <a href="#" title="" class="pat7"><img src="<?php echo $this->doc()->getBaseUrl(); ?>assets/images/switcher/8.png" alt="" /></a>
    <a href="#" title="" class="pat8"><img src="<?php echo $this->doc()->getBaseUrl(); ?>assets/images/switcher/9.png" alt="" /></a>
    <a href="#" title="" class="pat10"><img src="<?php echo $this->doc()->getBaseUrl(); ?>assets/images/switcher/10.png" alt="" /></a>
    <a href="#" title="" class="pat9"><img src="<?php echo $this->doc()->getBaseUrl(); ?>assets/images/switcher/1.png" alt="" /></a>
</div>
-->

<!-- Left side content -->
<div id="leftSide">
    <div class="logo"><!--<a href="index.html"><img src="images/logo.png" alt="" /></a>--></div>

    <div class="sidebarSep mt0"></div>

    <!-- Search widget -->
    <form action="" class="sidebarSearch">
        <input type="text" name="search" placeholder="search..." id="ac" />
        <input type="submit" value="" />
    </form>

    <div class="sidebarSep"></div>

    <!-- Left navigation -->
    <ul id="menu" class="nav">
        <li class="dash"><a href="index.html" title=""><span>Dashboard</span></a></li>
        <li class="charts"><a href="charts.html" title=""><span>Statistics and charts</span></a></li>
        <li class="forms"><a href="#" title="" class="exp"><span>Forms stuff</span><strong>4</strong></a>
            <ul class="sub">
                <li><a href="forms.html" title="">Form elements</a></li>
                <li><a href="form_validation.html" title="">Validation</a></li>
                <li><a href="form_editor.html" title="">WYSIWYG and file uploader</a></li>
                <li class="last"><a href="form_wizards.html" title="">Wizards</a></li>
            </ul>
        </li>
        <li class="ui"><a href="ui_elements.html" title=""><span>Interface elements</span></a></li>
        <li class="tables"><a href="tables.html" title="" class="exp"><span>Tables</span><strong>3</strong></a>
            <ul class="sub">
                <li><a href="table_static.html" title="">Static tables</a></li>
                <li><a href="table_dynamic.html" title="">Dynamic table</a></li>
                <li class="last"><a href="table_sortable_resizable.html" title="">Sortable &amp; resizable tables</a></li>
            </ul>
        </li>
        <li class="widgets"><a href="#" title="" class="active exp" id="current"><span>Widgets and grid</span><strong>2</strong></a>
            <ul class="sub">
                <li class="this"><a href="widgets.html" title="">Widgets</a></li>
                <li class="last"><a href="grid.html" title="">Grid</a></li>
            </ul>
        </li>
        <li class="errors"><a href="#" title="" class="exp"><span>Error pages</span><strong>6</strong></a>
            <ul class="sub">
                <li><a href="403.html" title="">403 page</a></li>
                <li><a href="404.html" title="">404 page</a></li>
                <li><a href="405.html" title="">405 page</a></li>
                <li><a href="500.html" title="">500 page</a></li>
                <li><a href="503.html" title="">503 page</a></li>
                <li class="last"><a href="offline.html" title="">Website is offline</a></li>
            </ul>
        </li>
        <li class="files"><a href="file_manager.html" title=""><span>File manager</span></a></li>
        <li class="typo"><a href="#" title="" class="exp"><span>Other pages</span><strong>3</strong></a>
            <ul class="sub">
                <li><a href="typography.html" title="">Typography</a></li>
                <li><a href="calendar.html" title="">Calendar</a></li>
                <li class="last"><a href="gallery.html" title="">Gallery</a></li>
            </ul>
        </li>
    </ul>

    <div class="sidebarSep"></div>

    <!-- Sidebar profile -->
    <div class="sideProfile">
        <a href="#" title="" class="profileFace"><img src="images/face1.png" alt="" /></a>
        <span>Howdy <strong>Eugene!</strong></span>
        <span>You have <a href="#" title="">2</a> unread mails</span>
        <div class="clear"></div>
        <div class="sidedd">
            <span class="goUser">Eugene Kopyov</span>
            <ul class="sideDropdown">
                <li><a href="#" title=""><img src="images/icons/topnav/profile.png" alt="" />My profile</a></li>
                <li><a href="#" title=""><img src="images/icons/topnav/messages.png" alt="" />My messages</a></li>
                <li><a href="#" title=""><img src="images/icons/topnav/tasks.png" alt="" />My tasks</a></li>
                <li><a href="#" title=""><img src="images/icons/topnav/settings.png" alt="" />My settings</a></li>
                <li><a href="#" title=""><img src="images/icons/topnav/logout.png" alt="" />Logout</a></li>
            </ul>
        </div>
    </div>

    <div class="sidebarSep"></div>

    <!-- Statistics -->
    <div class="numStats">
        <ul>
            <li>1248<span>visitors</span></li>
            <li>597<span>orders</span></li>
            <li class="last">981<span>reviews</span></li>
        </ul>
        <div class="clear"></div>
    </div>

    <div class="sidebarSep"></div>

    <!-- Icons group widget -->
    <div class="iconsGroup">
        <ul>
            <li><a href="#" title="" class="dUsers"></a></li>
            <li><a href="#" title="" class="dMessages"><span class="groupNum">9</span></a></li>
            <li><a href="#" title="" class="dMoney"></a></li>
        </ul>
        <div class="clear"></div>
    </div>

    <div class="sidebarSep"></div>

    <!-- General balance widget -->
    <div class="genBalance">
        <a href="#" title="" class="amount">
            <span>General balance:</span>
            <span class="balanceAmount">$10,900.36</span>
        </a>
        <a href="#" title="" class="amChanges">
            <strong class="sPositive">+0.6%</strong>
        </a>
    </div>

    <!-- Next update progress widget -->
    <div class="nextUpdate">
        <ul>
            <li>Next update in:</li>
            <li>23 hrs 14 min</li>
        </ul>
        <div class="pWrapper"><div class="progressG" title="78%"></div></div>
    </div>

    <div class="sidebarSep"></div>

    <!-- Progress bars -->
    <div class="pWrapper"><div class="progressO" title="30%"></div></div>
    <div class="pWrapper mt10"><div class="progressB" title="60%"></div></div>
    <div class="pWrapper mt10"><div class="progressR tipN" title="90%"></div></div>

    <div class="sidebarSep"></div>

    <!-- Sidebar buttons -->
    <a href="#" title="" class="sButton sBlue"><img src="images/icons/sPlus.png" alt="" /><span>Add new statement</span></a>
    <a href="#" title="" class="sButton sRed" style="margin-top: 12px;"><img src="images/icons/sPlus.png" alt="" /><span>Add new session</span></a>
    <a href="#" title="" class="sButton sGreen" style="margin-top: 12px;"><img src="images/icons/sPlus.png" alt="" /><span>Add new invoice</span></a>

    <div class="sidebarSep"></div>

    <!-- Rounded stats -->
    <div class="sRoundStats">
        <ul>
            <li>Visitors<a href="#" title=""><span class="roundPos">68%</span></a></li>
            <li>Sales<a href="#" title=""><span class="roundZero">0%</span></a></li>
            <li>Profit<a href="#" title=""><span class="roundNeg">0.6%</span></a></li>
        </ul>
        <div class="clear"></div>
    </div>
    <div class="nextUpdate">
        <div class="pWrapper"><div class="progressG" title="78%"></div></div>
        <ul>
            <li>Next update in:</li>
            <li>23 hrs 14 min</li>
        </ul>
    </div>

    <div class="sidebarSep"></div>

</div>


<!-- Right side -->
<div id="rightSide">

<!-- Top fixed navigation -->
<div class="topNav">
    <div class="wrapper">
        <div class="welcome"><a href="#" title=""><img src="images/userPic.png" alt="" /></a><span>Hi, Admin!</span></div>
        <div class="userNav">
            <ul>
                <li><a href="#" title=""><img src="images/icons/topnav/profile.png" alt="" /><span>Profile</span></a></li>
                <li><a href="#" title=""><img src="images/icons/topnav/tasks.png" alt="" /><span>Tasks</span></a></li>
                <li class="dd"><a title=""><img src="images/icons/topnav/messages.png" alt="" /><span>Messages</span><span class="numberTop">8</span></a>
                    <ul class="userDropdown">
                        <li><a href="#" title="" class="sAdd">new message</a></li>
                        <li><a href="#" title="" class="sInbox">inbox</a></li>
                        <li><a href="#" title="" class="sOutbox">outbox</a></li>
                        <li><a href="#" title="" class="sTrash">trash</a></li>
                    </ul>
                </li>
                <li><a href="#" title=""><img src="images/icons/topnav/settings.png" alt="" /><span>Settings</span></a></li>
                <li><a href="login.html" title=""><img src="images/icons/topnav/logout.png" alt="" /><span>Logout</span></a></li>
            </ul>
        </div>
        <div class="clear"></div>
    </div>
</div>

<!-- Responsive header -->
<div class="resp">
    <div class="respHead">
        <a href="index.html" title=""><img src="images/loginLogo.png" alt="" /></a>
    </div>

    <div class="cLine"></div>
    <div class="smalldd">
        <span class="goTo"><img src="images/icons/light/frames.png" alt="" />Content widgets</span>
        <ul class="smallDropdown">
            <li><a href="index.html" title=""><img src="images/icons/light/home.png" alt="" />Dashboard</a></li>
            <li><a href="charts.html" title=""><img src="images/icons/light/stats.png" alt="" />Statistics and charts</a></li>
            <li><a href="#" title="" class="exp"><img src="images/icons/light/pencil.png" alt="" />Forms stuff<strong>4</strong></a>
                <ul>
                    <li><a href="forms.html" title="">Form elements</a></li>
                    <li><a href="form_validation.html" title="">Validation</a></li>
                    <li><a href="form_editor.html" title="">WYSIWYG and file uploader</a></li>
                    <li class="last"><a href="form_wizards.html" title="">Wizards</a></li>
                </ul>
            </li>
            <li><a href="ui_elements.html" title=""><img src="images/icons/light/users.png" alt="" />Interface elements</a></li>
            <li><a href="tables.html" title="" class="exp"><img src="images/icons/light/frames.png" alt="" />Tables<strong>3</strong></a>
                <ul>
                    <li><a href="table_static.html" title="">Static tables</a></li>
                    <li><a href="table_dynamic.html" title="">Dynamic table</a></li>
                    <li class="last"><a href="table_sortable_resizable.html" title="">Sortable &amp; resizable tables</a></li>
                </ul>
            </li>
            <li><a href="#" title="" class="exp"><img src="images/icons/light/fullscreen.png" alt="" />Widgets and grid<strong>2</strong></a>
                <ul>
                    <li><a href="widgets.html" title="">Widgets</a></li>
                    <li class="last"><a href="grid.html" title="">Grid</a></li>
                </ul>
            </li>
            <li><a href="#" title="" class="exp"><img src="images/icons/light/alert.png" alt="" />Error pages<strong>6</strong></a>
                <ul class="sub">
                    <li><a href="403.html" title="">403 page</a></li>
                    <li><a href="404.html" title="">404 page</a></li>
                    <li><a href="405.html" title="">405 page</a></li>
                    <li><a href="500.html" title="">500 page</a></li>
                    <li><a href="503.html" title="">503 page</a></li>
                    <li class="last"><a href="offline.html" title="">Website is offline</a></li>
                </ul>
            </li>
            <li><a href="file_manager.html" title=""><img src="images/icons/light/files.png" alt="" />File manager</a></li>
            <li><a href="#" title="" class="exp"><img src="images/icons/light/create.png" alt="" />Other pages<strong>3</strong></a>
                <ul>
                    <li><a href="typography.html" title="">Typography</a></li>
                    <li><a href="calendar.html" title="">Calendar</a></li>
                    <li class="last"><a href="gallery.html" title="">Gallery</a></li>
                </ul>
            </li>
        </ul>
    </div>
    <div class="cLine"></div>
</div>

<?php echo $this->doc()->getComponentData(); ?>

<!-- Footer line -->
<div id="footer">
    <div class="wrapper">Hi, <a href="mailto:tronghieu.luu@gmail.com" title="">Lưu Trọng Hiếu</a></div>
</div>

</div>

<div class="clear"></div>
</body>
</html>