<script>
    $(document).ready(function(){
        $(".datepicker").datepicker();
    });
</script>
<div class="title"><h5>THÊM MỚI NHÓM PHÂN LOẠI</h5></div>
<?php if(@$title_err) { ?>
<div class="pt20">
    <div class="nNote nWarning hideit">
        <p><strong>WARNING: </strong><?php echo @$title_err;?></p>
    </div>
</div>
<?php } ?>
<form class="mainForm" action="" method="post">

<!-- Input text fields -->
<fieldset>
    <div class="widget first">
        <div class="head"><h5 class="iList">Thêm mới</h5></div>
        <div class="rowElem noborder">
            <label>Title:</label>
            <div><input type="text" name="title" style="width: 150px" /></div>
            <div class="fix"></div>
        </div>
        <div class="rowElem">
            <label>Danh sách phân loại:</label><textarea name="taxonamys" style="width: 525px"></textarea>
        </div>
        <div class="fix"></div>
        </div>
        <div class="rowElem">
            <input type="submit" class="rowElem greyishBtn submitForm" name="add" value="Cập nhật" />
        </div>

        <div class="fix"></div>
    </div>
</fieldset>
</form>