<!-- Login form area -->
<div style="width: 25%">
    <div style="float: left">
        <form action="" method="post">
            <table>
                <tr>
                    <td>User</td>
                    <td><input type="text" name="username"></td>

                </tr>
                <tr>
                    <td>Pass</td>
                    <td><input type="text" name="password"></td>
                </tr>
                <tr>
                    <td colspan="2">
                        <input type="submit" value="Login">
                    </td>
                </tr>
            </table>
        </form>
    </div>
    <div style="float: right">
        <a href="">Google</a>
        <br>
        <a href="">Yahoo</a>
        <br>
        <a href="">FaceBook</a>
        <br>
    </div>
</div>