<!DOCTYPE HTML>
<?php $document = \Flywheel\Factory::getDocument();?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://ogp.me/ns#"
      xmlns:fb="https://www.facebook.com/2008/fbml">
<head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link rel="icon" type="image/x-icon" href="<?php echo $document->getPublicPath(); ?>assets/images/favicon.ico" />
        <meta http-equiv="Content-language" content="vi" />
        <title><?php echo $document->title; ?></title>
        <meta name="description" content="<?php echo $document->description; ?>" />
        <meta name="keywords" content="<?php echo $document->keyword ?>" />

        <meta property="fb:app_id" content="344284628973709"/>

        <?php echo $document->og(); ?>
        <base href="<?php echo $document->getBaseUrl(); ?>" />
        <link rel="canonical" href="<?php echo $document->canonicalUrl; ?>" />
        <?php echo $document->css(); ?>
        <script type="text/javascript" src="<?php echo $document->getBaseUrl(); ?>assets/js/jquery/jquery-1.7.1.min.js"></script>
        <?php echo $document->js('TOP') ?>

    </head>

<body class="<?php echo (isset($classbody)?$classbody:'rs'); ?> <?php if(isset($classPublic)){ echo $classPublic;}  ?>">

<?php echo $document->getComponentData();?>
<?php echo $document->js('BOTTOM') ?>

</body>
</html>


