<div class="leftNav">
	<ul id="menu">
		<li class="dash"><a href="index.html" title=""><span>Người dùng</span></a></li>
		<li class="graphs"><a href="charts.html" title=""><span>Danh mục</span></a></li>
		<li class="forms"><a href="form_elements.html" title=""><span>Sản phẩm</span></a></li>
		<li class="login"><a href="ui_elements.html" title=""><span>Đơn hàng</span></a></li>
		<li class="typo"><a href="typo.html" title=""><span>Nhân viên</span><span class="numberLeft">6</span></a></li>
		<li class="tables"><a href="tables.html" title="" class="active"><span>Phân quyền</span></a></li>
		
	</ul>
</div>