<!-- Main content wrapper -->
<div class="loginWrapper">
    <!--<div class="loginLogo"><img src="<?php echo $this->doc()->getBaseUrl(); ?>assets/images/loginLogo.png" alt="" /></div>-->
    <?php if (isset($error) && !empty($error)) : ?>
    <p style="color:red; text-align: center"><?php echo implode('<br />', UserAuth::errorLabel($error));?></p>
    <?php endif; ?>
    <div class="widget">
        <div class="title"><img src="<?php echo $this->doc()->getBaseUrl(); ?>assets/images/icons/dark/files.png" alt="" class="titleIcon" /><h6>Login panel</h6></div>
        <form action="" id="validate" class="form" method="POST">
            <fieldset>
                <div class="formRow">
                    <label for="username">Username:</label>
                    <div class="loginInput">
                        <input type="text" value="<?php echo $username ?>" name="username" class="validate[required]" id="username" />
                    </div>
                    <div class="clear"></div>
                </div>

                <div class="formRow">
                    <label for="password">Password:</label>
                    <div class="loginInput">
                        <input type="password" name="password" class="validate[required]" id="password" />
                    </div>
                    <div class="clear"></div>
                </div>

                <div class="loginControl">
                    <!-- <div class="rememberMe"><input type="checkbox" id="remMe" name="remMe" /><label for="remMe">Remember me</label></div>-->
                    <input type="submit" value="Log me in" class="dredB logMeIn" />
                    <div class="clear"></div>
                </div>
            </fieldset>
        </form>
    </div>
</div>