<?php $doc = PiCms::getDocument() ?>
<div class="language">
    <div class="current-lang">
        <img src="<?php echo $doc->getBaseUrl() ?>assets/images/<?php echo $selected_language->sef?>.gif" alt="<?php echo $selected_language->title?>">
        <span><?php echo $selected_language->title?></span>
        <i class="icon iPickDownW"></i>
    </div>
    <ul id="sys-lst-language" class="rs">
        <?php foreach ($languages as $lang) : ?>
        <li data-lang="<?php echo $lang->sef?>">
            <img src="<?php echo $doc->getBaseUrl() ?>assets/images/<?php echo $lang->sef?>.gif" alt="<?php echo $lang->title ?>">
            <span><?php echo $lang->title ?></span>
        </li>
        <?php endforeach; ?>
    </ul>
    <!--<form id="sys_choose_lang" style="display: none" method="POST">
        <select name="lang" id="sys_language_select">
            <?php foreach ($languages as $lang) : ?>
            <option value="<?php echo $lang->sef ?>"><?php echo $lang->sef ?></option>
            <?php endforeach; ?>
        </select>
    </form> -->

</div>