<!-- Login form area -->

<form action="" method="post">
    <table>
        <tr>
            <td>User</td>
            <td><input type="text" name="username"></td>

        </tr>
        <tr>
            <td>Pass</td>
            <td><input type="text" name="password"></td>
        </tr>
        <tr>
            <td>Repass</td>
            <td><input type="text" name="repass"></td>
        </tr>
        <tr>
            <td>Email</td>
            <td><input type="text" name="email"></td>
        </tr>
        <tr>
            <td colspan="2">
                <input type="submit" value="Registry">
            </td>
        </tr>
    </table>
</form>
