<div class="title"><h5>QUẢN TRỊ PHÂN LOẠI</h5></div>
<!-- Dynamic table -->
<p style="text-align: right">
    <a href="<?php echo Ming_Factory::getDocument()->getBaseUrl().'taxonomy_group/add'?>">Thêm mới</a>
</p>
<div class="table" style="margin-top: 10px">

<div class="head"><h5 class="iFrames">Danh sách phân loại</h5></div>

<table cellpadding="0" cellspacing="0" border="0" class="display" id="example">
<thead>
<tr>
    <th>STT</th>
    <th>Title</th>
    <th>Taxonomy</th>
    <th>Option</th>

</tr>
</thead>
<tbody>
<?php

$i = 0;
if(isset($taxo_groups))

foreach($taxo_groups as $taxo_group) {?>
    <tr class="gradeX">
        <td><?php echo ($i+=1); ?></td>

        <td><?php echo $taxo_group['title'];?></td>
        <td class="center">
            <?php if($taxo_group['taxonomys'] && !empty($taxo_group['taxonomys'])  ){
                foreach ($taxo_group['taxonomys'] as $taxonamy){
                    echo $taxonamy['title'].' ( '.@$taxonamy['slug'].' ) '.'<br/>';
                }
            }?>
        </td>
        <td class="center">
            <a href="<?php echo Ming_Factory::getRouter()->getBaseUrl().'taxonomy_group/edit?id='.$taxo_group['_id']; ?>">Sửa</a>
            &nbsp; || &nbsp;
            <a href="<?php echo Ming_Factory::getRouter()->getBaseUrl().'taxonomy_group/remove?id='.$taxo_group['_id']; ?>">Xóa</a>
        </td>
    </tr>
<?php } ?>
</tbody>
</table>
</div>