<ul class="rs">
    <li>
        <a href="home.html">Home</a>
    </li>
    <li>
        <a href="about.html">About us</a>
    </li>
    <li>
        <a href="training-event.html">Training/event</a>
    </li>
    <li>
        <a href="#">Resources</a>
    </li>
    <li>
        <a href="#">Online Conversation</a>
    </li>
    <li>
        <a href="news-list.html">News</a>
    </li>
    <li>
        <a href="contact.html">Contact us</a>
    </li>
    <li>
        <a href="#">Sitemap</a>
    </li>
    <li>
        <a href="#">Rss</a>
    </li>
</ul>
